<?php

/**
 * Implements hook_migrate_api().
 */
function pipe_migrate_migrate_api() {
  $migrations = array(
    // Taxonomy term.
    'PipeMipTaxonomyTerms' => array('class_name' => 'PipeMipTaxonomyTerms'),
    'PipeNipTaxonomyTerms' => array('class_name' => 'PipeNipTaxonomyTerms'),
    'PipeRipTaxonomyTerms' => array('class_name' => 'PipeRipTaxonomyTerms'),
    'PipeMeetingTypeTaxonomyTerms'  => array('class_name' => 'PipeMeetingTypeTaxonomyTerms'),
    'PipeActionStatusTaxonomyTerms' => array('class_name' => 'PipeActionStatusTaxonomyTerms'),
    'PipeContractStatusTaxonomyTerms' => array('class_name' => 'PipeContractStatusTaxonomyTerms'),
    'PipeIpStatusTaxonomyTerms' => array('class_name' => 'PipeIpStatusTaxonomyTerms'),
    'PipePortfolioSectorsTaxonomyTerms' => array('class_name' => 'PipePortfolioSectorsTaxonomyTerms'),
    'PipeRegionTaxonomyTerms' => array('class_name' => 'PipeRegionTaxonomyTerms'),
    'PipeCountryTaxonomyTerms' => array('class_name' => 'PipeCountryTaxonomyTerms'),
    'PipeSsfTaxonomyTerms' => array('class_name' => 'PipeSsfTaxonomyTerms'),

    // Node.
    'PipeActionNodes'  => array('class_name' => 'PipeActionNodes'),
    'PipeContractNodes'  => array('class_name' => 'PipeContractNodes'),
    'PipeDocumentNodes'  => array('class_name' => 'PipeDocumentNodes'),
    'PipeEcRiNodes'  => array('class_name' => 'PipeEcRiNodes'),
    'PipeEnvelopeNodes' => array('class_name' => 'PipeEnvelopeNodes'),
    'PipeLocalRiNodes' => array('class_name' => 'PipeLocalRiNodes'),
    'PipeMeetingNodes'  => array('class_name' => 'PipeMeetingNodes'),
    'PipeProjectNodes' => array('class_name' => 'PipeProjectNodes'),
    'PipeUnitInstitutionNodes' => array('class_name' => 'PipeUnitInstitutionNodes'),
    'PipeUnitDgNodes' => array('class_name' => 'PipeUnitDgNodes'),
    'PipeUnitMdNodes' => array('class_name' => 'PipeUnitMdNodes'),
    'PipeUnitDdgNodes' => array('class_name' => 'PipeUnitDdgNodes'),
    'PipeUnitDirectorateNodes' => array('class_name' => 'PipeUnitDirectorateNodes'),
    'PipeUnitDelegationNodes' => array('class_name' => 'PipeUnitDelegationNodes'),
    'PipeUnitRegionalisedDelegationNodes' => array('class_name' => 'PipeUnitRegionalisedDelegationNodes'),
    'PipeUnitDivisionNodes' => array('class_name' => 'PipeUnitDivisionNodes'),
    'PipeUnitUnitNodes' => array('class_name' => 'PipeUnitUnitNodes'),
    'PipeUnitSectionNodes' => array('class_name' => 'PipeUnitSectionNodes'),

    // File.
    'PipeFiles' => array('class_name' => 'PipeFiles'),
    'PipeUserPictures' => array('class_name' => 'PipeUserPictures'),

    // User.
    'PipeUsers' => array('class_name' => 'PipeUsers'),
    'PipeUserInfo' => array('class_name' => 'PipeUserInfo'),
  );

  $api = array(
    'api' => 2,
    'migrations' => $migrations,
  );
  return $api;
}
