<?php
/**
 * @file
 * Code for the drupal_angular_general feature.
 */

include_once 'drupal_angular_general.features.inc';

/**
 * Implements hook_menu().
 */
function drupal_angular_general_menu() {
  $items['create/content'] = array(
    'title' => 'Add content',
    'access callback' => 'node_access',
    'access arguments' => array('create', 'content'),
    'page callback' => 'drupal_angular_general_form_page',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function drupal_angular_general_theme() {
  $theme['drupal_angular_general_angular_form'] = array(
    'template' => 'restful-angular-form',
    'path' => drupal_get_path('module', 'drupal_angular_general') . '/templates',
    'variables' => array(
      'url' => NULL
    ),
  );

  return $theme;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupal_angular_general_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Page callback; Load the AngularJs form.
 */
function drupal_angular_general_form_page() {
  $bower_path = libraries_get_path('bower_components');

  // Load the libraries.
  drupal_add_js($bower_path . '/angular/angular.js');

  // JSON pretty print library.
  drupal_add_js($bower_path . '/ng-prettyjson/dist/ng-prettyjson.min.js');
  drupal_add_css($bower_path . '/ng-prettyjson/dist/ng-prettyjson.min.css');

  // Select2.
  drupal_add_js($bower_path . '/select2/select2.js');
  drupal_add_css($bower_path . '/select2/select2.css');
  drupal_add_js($bower_path . '/angular-ui-select2/src/select2.js');

  // Bootstrap DatePicker.
  drupal_add_css($bower_path . '/angular-bootstrap-datetimepicker/src/css/datetimepicker.css');
  drupal_add_js($bower_path . '/moment/moment.js');
  drupal_add_js($bower_path . '/bootstrap/dist/js/bootstrap.js');
  drupal_add_js($bower_path . '/angular-bootstrap-datetimepicker/src/js/datetimepicker.js');

  // Load our custom app.
  $app_path = $bower_path . '/restful-app/dist';
  drupal_add_js($app_path . '/restful-app.js');
  drupal_add_css($app_path . '/css/restful-app.css');

  // Get all categories terms.
  $v = taxonomy_vocabulary_machine_name_load('categories');
  $terms = taxonomy_get_tree($v->vid);

  $categories = array();

  foreach ($terms as $term) {
    $categories[$term->tid]['tid'] = $term->tid;
    $categories[$term->tid]['name'] = $term->name;
  }

  // Pass info via Drupal.settings.
  $settings['drupalAngular'] = array(
    'basePath' => url('', array('absolute' => TRUE)),
    'csrfToken' => drupal_get_token(\RestfulInterface::TOKEN_VALUE),
    'data' => array(
      'entity' => array(
        'label' => NULL,
        'categories' => $categories
      ),
    ),
  );
  drupal_add_js($settings, 'setting');

  // Theme function simply declares the angular app, and ng-includes the app's
  // view.
  $url = url($app_path . '/views/main.html', array('absolute' => TRUE));
  return theme('drupal_angular_general_angular_form', array('url' => $url));
}

